import {
  LayoutDashboard,
  Users,
  Shield,
  Building2,
  Sliders,
  Database,
  Trophy,
  Bell,
  FileText,
  ScrollText,
  Settings,
  UsersRound,
  IdCard,
  Map as MapIcon,
  FileBarChart,
  AlertTriangle,
  Presentation,
  GraduationCap,
  CheckCircle2,
  ListChecks,
  Link as LinkIcon,
  GitCompareArrows,
  AlertCircle,
  History,
  ClipboardCheck,
  Briefcase,
  Route,
  ListTodo,
  TrendingUp,
  StickyNote,
  Lightbulb,
  Activity,
  Target,
  Wand2,
  Award,
  Send,
  Inbox,
  type LucideIcon,
} from 'lucide-react';
import type { RoleCode } from '@/lib/auth/roles';

export interface SidebarItem {
  label: string;
  href: string;
  icon: LucideIcon;
}

export const SIDEBAR_ITEMS: Record<RoleCode, SidebarItem[]> = {
  admin: [
    { label: 'لوحة النظام', href: '/admin/dashboard', icon: LayoutDashboard },
    { label: 'إدارة المستخدمين', href: '/admin/users', icon: Users },
    { label: 'الأدوار والصلاحيات', href: '/admin/roles', icon: Shield },
    { label: 'الهيكل التنظيمي', href: '/admin/organization', icon: Building2 },
    { label: 'محاور التقييم والأوزان', href: '/admin/weights', icon: Sliders },
    { label: 'البيانات التجريبية', href: '/admin/demo-data', icon: Database },
    { label: 'المسابقات الوظيفية', href: '/admin/competitions', icon: Trophy },
    { label: 'التذكيرات والإشعارات', href: '/admin/notifications', icon: Bell },
    { label: 'النصوص التعريفية', href: '/admin/page-content', icon: FileText },
    { label: 'سجل التدقيق', href: '/admin/audit-logs', icon: ScrollText },
    { label: 'إعدادات المنصة', href: '/admin/settings', icon: Settings },
  ],
  president: [
    { label: 'لوحة القيادة العليا', href: '/executive/dashboard', icon: LayoutDashboard },
    { label: 'قائمة المرشحين', href: '/executive/candidates', icon: UsersRound },
    { label: 'البطاقات القيادية', href: '/executive/candidates', icon: IdCard },
    { label: 'مقارنة المرشحين', href: '/executive/compare', icon: IdCard },
    { label: 'خريطة الملاءمة التنظيمية', href: '/organization/map', icon: MapIcon },
    { label: 'التقارير التنفيذية', href: '/executive/reports', icon: FileBarChart },
    { label: 'المسابقات الوظيفية', href: '/executive/competitions', icon: Trophy },
    { label: 'توصيات المنصة', href: '/executive/recommendations', icon: Lightbulb },
    { label: 'التنبيهات القيادية', href: '/executive/alerts', icon: AlertTriangle },
    { label: 'مركز العرض التنفيذي', href: '/executive-center', icon: Presentation },
    { label: 'المستشارون', href: '/executive/advisors', icon: GraduationCap },
    { label: 'إدارة المستخدمين', href: '/executive/users', icon: Users },
  ],
  advisor: [
    { label: 'لوحة المستشار', href: '/advisor/dashboard', icon: LayoutDashboard },
    { label: 'المرشحون المصرح بهم', href: '/advisor/candidates', icon: UsersRound },
    { label: 'بطاقات المرشحين', href: '/advisor/cards', icon: IdCard },
    { label: 'خريطة الملاءمة', href: '/organization/map', icon: MapIcon },
    { label: 'التقارير المصرح بها', href: '/advisor/reports', icon: FileBarChart },
    { label: 'ملاحظاتي الاستشارية', href: '/advisor/notes', icon: StickyNote },
  ],
  governance: [
    { label: 'لوحة لجنة الحوكمة', href: '/governance/dashboard', icon: LayoutDashboard },
    { label: 'مراجعة ملفات المرشحين', href: '/governance/reviews', icon: ClipboardCheck },
    { label: 'اعتماد المقيمين', href: '/governance/evaluators', icon: CheckCircle2 },
    { label: 'إنشاء روابط التقييم', href: '/governance/evaluation-links', icon: LinkIcon },
    { label: 'متابعة تقييم 360', href: '/governance/360', icon: Activity },
    { label: 'مراجعة النتائج', href: '/governance/results', icon: ListChecks },
    { label: 'التظلمات', href: '/governance/appeals', icon: AlertCircle },
    { label: 'قرارات اللجنة', href: '/governance/decisions', icon: ListChecks },
    { label: 'حالات تضارب المصالح', href: '/governance/conflicts', icon: AlertTriangle },
    { label: 'سجل الحوكمة', href: '/governance/audit', icon: History },
  ],
  hr: [
    { label: 'لوحة الموارد البشرية', href: '/hr/dashboard', icon: LayoutDashboard },
    { label: 'قائمة المتقدمين', href: '/hr/candidates', icon: UsersRound },
    { label: 'متابعة اكتمال الملفات', href: '/hr/completion-tracking', icon: ListChecks },
    { label: 'المسابقات الوظيفية', href: '/hr/competitions', icon: Trophy },
    { label: 'مسارات التقييم', href: '/hr/evaluation-tracks', icon: Route },
    { label: 'خطط التطوير الفردية', href: '/hr/development-plans', icon: Target },
    { label: 'تقارير التطوير', href: '/hr/development-reports', icon: TrendingUp },
    { label: 'إشعارات المتابعة', href: '/hr/notifications', icon: Bell },
    { label: 'ملاحظات الموارد البشرية', href: '/hr/notes', icon: StickyNote },
  ],
  candidate: [
    { label: 'لوحة المستخدم', href: '/candidate/dashboard', icon: LayoutDashboard },
    { label: 'الملف القيادي', href: '/candidate/profile', icon: IdCard },
    { label: 'المبادرات والإنجازات', href: '/candidate/initiatives', icon: Award },
    { label: 'مؤشرات الأداء', href: '/candidate/kpis', icon: Activity },
    { label: 'الاختبارات الذكية', href: '/candidate/assessments', icon: Wand2 },
    { label: 'تقييم 360', href: '/candidate/360', icon: UsersRound },
    { label: 'النتيجة', href: '/candidate/result', icon: Award },
    { label: 'خطة التطوير الفردية', href: '/candidate/development-plan', icon: Target },
    { label: 'التظلمات', href: '/candidate/appeals', icon: Send },
    { label: 'الإشعارات', href: '/candidate/notifications', icon: Inbox },
  ],
};
